version: '3.8'
services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - pgdata:/var/lib/postgresql/data 

    app:
      build:
        context: .
        dockerfile: Dockerfile
        container_name: docker-test-app
        environment:
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        ports:
        - "3000:3000"
        depends_on:
          - postgres

  volumes:
      pgdata:
      # driver: local      