# version: '3.8'
services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 2002
      POSTGRES_DB: postgres  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 

  app:
    build:
      network: host
      context: ./
      dockerfile: Dockerfile
    container_name: docker-test-app
    environment:
      - DATABASE_URL=postgresql://postgres:2002@postgres:5432/postgres
    ports:
      - 3000:3000 
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

