name: Deploy to Staging
on:
  push:
    branches: ["main"]
    paths:
      - "Week 25/bms/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Week 25/bms

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PRIVATE_SSH_KEY }}
          # port: ${{ secrets.PORT }}
          script: |
            echo "Deploying to staging server..."
            cd 100xDevs-Cohort3-WebDev-and-Devops
            cd 'Week 25/bms'
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart all
            echo "Deployment to staging server completed successfully."
